# GLOBAL VARIABLES

# GOAL LOCATION (Milestone 1)
GOAL_X = 0.6
GOAL_Y = 0.6
GOAL_TH = 0

# GOAL LOCATIONS (Milestone2)
# Format = [X, Y, THETA]
ORIGIN = [0,0,0]
goal_A = [0.5,0.5,0]
goal_B = [0.2,0.2,0]
goal_C = [1,1,0]


# Physical Parameters
WHEEL_SEPARATION = 0.220 #220mm
WHEEL_RADIUS = 0.028 #28mm

# Chosen/Calibrated Parameters
DIST_THRESHOLD = 0.2
ANG_THRESHOLD = 0.5
MOTOR_SPEED = 
SHAFTENC_STEPS2DEG = 
ULT_MIN_DIST = 
PACKAGEDROP_OFFSET = 

# Pin Mappings
SERVO_PIN = 
ULT_FRONT_ECHO = 
ULT_FRONT_TRIG = 
ULT_RIGHT_ECHO = 
ULT_RIGHT_TRIG = 
ULT_LEFT_ECHO = 
ULT_LEFT_TRIG = 
ULT_BKLEFT_ECHO = 
ULT_BKLEFT_TRIG = 
ULT_BKRIGHT_ECHO = 
ULT_BKRIGHT_TRIG = 
ROTENC_RIGHT_A = 17
ROTENC_RIGHT_B = 27
ROTENC_LEFT_A = 20
ROTENC_LEFT_B = 21
MOTOR_L_FORWARD = 5
MOTOR_L_BACKWARD = 6
MOTOR_L_ENABLE = 12
MOTOR_R_FORWARD = 23
MOTOR_R_BACKWARD = 24
MOTOR_R_ENABLE = 13
