# GLOBAL VARIABLES
# Physical Parameters
WHEEL_LENGTH = 
WHEEL_RADIUS = 

# Chosen/Calibrated Parameters
MOTOR_SPEED = 
SHAFTENC_STEPS2DEG = 
ULTRA_MIN_DIST = 
PACKAGEDROP_OFFSET = 

# Pin Mappings
ULT_FRONT_ECHO = 
ULT_FRONT_TRIG = 
ULT_RIGHT_ECHO = 
ULT_RIGHT_TRIG = 
ULT_LEFT_ECHO = 
ULT_LEFT_TRIG = 
