# GLOBAL VARIABLES

# GOAL LOCATION (Milestone 1)
GOAL_X = 0.6
GOAL_Y = 0.6
GOAL_TH = 0

# GOAL LOCATIONS (Milestone2)
# Format = [X, Y, THETA]
ORIGIN = [0,0,0]
goal_A = [0.5,0.5,0]
goal_B = [0.2,0.2,0]
goal_C = [1,1,0]

# Physical Parameters
WHEEL_SEPARATION = 0.220 #220mm
WHEEL_RADIUS = 0.028 #28mm

# Chosen/Calibrated Parameters
DIST_THRESHOLD = 0.2
ANG_THRESHOLD = 0.5
# MOTOR_SPEED = 
# SHAFTENC_STEPS2DEG = 
# ULT_MIN_DIST = 
# PACKAGEDROP_OFFSET = 

# Ultrasonic threshold
THRESHOLD_F = 20
THRESHOLD_LR = 15

# Pin Mappings
SERVO_PIN = 22
ULT_FRONT_ECHO = 26
ULT_FRONT_TRIG = 20
ULT_SIDEFRONT_ECHO = 
ULT_SIDEFRONT_TRIG = 12
ULT_SIDEBACK_ECHO = 19
ULT_SIDEBACK_TRIG = 21

ROTENC_RIGHT_A = 17 # Might need flip
ROTENC_RIGHT_B = 27 # Might need flip
ROTENC_LEFT_A = 14 # Might need flip
ROTENC_LEFT_B = 15 # Might need flip
MOTOR_L_FORWARD = 24 #
MOTOR_L_BACKWARD = 23 #
MOTOR_L_ENABLE = 12 
MOTOR_R_FORWARD = 7 #
MOTOR_R_BACKWARD = 1 #   
MOTOR_R_ENABLE = 13 #

# Encoder Power May also need flip
